
openapi: 3.0.0
info:
  title: STD24160
  description: This is a specification of STD24160
  version: "1.0.0"
servers:
  - url: http://localhost:8000
components:
  schemas:
    Phone:
      type: object
      properties:
        id:
          type: string
        brand:
          type: string
        model:
          type: string
        characteristics:
          type: object
          properties:
            ram_memory:
              type: integer
            rom_memory:
              type: integer 